apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-pipeline-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven-pipeline-app
  template:
    metadata:
      labels:
        app: maven-pipeline-app
    spec:
      containers:
      - name: maven-ecr
        image: 740955001227.dkr.ecr.us-east-1.amazonaws.com/maven-ecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maven-pipeline-app
    k8s-app: maven-pipeline-app
  name: maven-pipeline-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: maven-pipeline-app