apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-devops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geo-devops
  template:
    metadata:
      labels:
        app: geo-devops
    spec:
      containers:
      - name: geo-devops
        image: 740955001227.dkr.ecr.us-east-1.amazonaws.com/geo-devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geo-devops
    k8s-app: geo-devops
  name: geo-devops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: geo-devops