apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-ecr-repo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-ecr-repo-app
  template:
    metadata:
      labels:
        app: eks-ecr-repo-app
    spec:
      containers:
      - name: eks-ecr-repo
        image: 740955001227.dkr.ecr.us-east-1.amazonaws.com/eks-ecr-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eks-ecr-repo-app
    k8s-app: eks-ecr-repo-app
  name: eks-ecr-repo-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: eks-ecr-repo-app