apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo_ecr_repo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geo_ecr_repo-app
  template:
    metadata:
      labels:
        app: geo_ecr_repo-app
    spec:
      containers:
      - name: geo_ecr_repo
        image: 740955001227.dkr.ecr.us-east-1.amazonaws.com/geo_ecr_repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geo_ecr_repo-app
    k8s-app: geo_ecr_repo-app
  name: geo_ecr_repo-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: geo_ecr_repo-app